### ISSUE TITLE
Selfhosting teodle for other streamers

### ISSUE THREAD

**Issue by Akashic101** [Zaczero/teodle#2]
I am thinking about bringing this idea to a friend who streams as well and was firstly wondering if this would be allowed. If it is, could there be an explanation on how to host it? I assume I would have to first build the docker-image, edit the .env and then run it? Python is not a language I understand so any help would be appreciated :D

**Comment by Zaczero** [comment]
> if this would be allowed

Of course yes.

> could there be an explanation on how to host it

**I will prepare some detailed instructions in the coming days.**

To give you an idea now, the steps would be more or less like this:
* Change the branding of the app (unless you want to play Teodle as 'Teo' ;-)).
  * This includes images in https://github.com/Zaczero/teodle/tree/main/static/img
  * But also HTML stuff in https://github.com/Zaczero/teodle/tree/main/templates
* Build the Docker image and upload it somewhere. Alternatively, you can skip Docker completely and manually install the app. It's very simple — all the steps can be found in https://github.com/Zaczero/teodle/blob/main/Dockerfile (it's Python with Pipenv as a package manager).
* Configure the environment variables: `TTV_TOKEN`, `TTV_USERNAME`, `TTV_CHANNEL`.
  * You will need one Twitch account to listen on chat, because the streamer does not need to log in.
  * The token can be retrieved using https://www.twitchapps.com/tmi/.
  * The username is simply the username of the account that the token belongs to.
  * The channel is a streamer's channel name.

**Comment by Akashic101** [comment]
First of all thank you for sharing this great project with everyone :D I gave it a shot and filled out the `.env` file with the required infos, however after I build the image with `docker build .` and trying to run it I get `KeyError: 'TTV_TOKEN'` which I would assume means that docker cannot find the .env file. Is there any trick that I am missing?

**Comment by Zaczero** [comment]
That's because .env is only used in manual deployment + during development. Docker envs must be set using docker or docker-compose. Publishing .env secrets in a docker image is never a good idea (see: -e as env). You will also have to mount the clips.txt file (see: -v as volume). I will provide more details soon.

**Comment by Zaczero** [comment]
https://github.com/Zaczero/teodle#deployment
